"""====MAIN FILE====

"## File sourcing

source ~/.vim/rc/plug.vim
source ~/.vim/rc/plugin_opts.vim
source ~/.vim/rc/commands.vim 
source ~/.vim/rc/interface.vim 
source ~/.vim/rc/syntax.vim 

"---Désactive safe writing
set backupcopy=yes

"---Autoreload file
set autoread


"-------Autosourcing 

augroup autosourcing
	 autocmd!
	 autocmd BufWritePost vimrc source %
augroup END

"-------Setting temp dirs
set backupdir=$HOME/.vim/backup//
set backupdir=$HOME/.vim/swap//
set backupdir=$HOME/.vim/undo//

"--- Source local .vimrc.local if exists

if filereadable(expand("$HOME/.vimrc.local"))
    source $HOME/.vimrc.local
endif

